---
title: "Lab 00 - Hello IDS!"
author: "Sean"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
```

### Exercises 16-17

We set up the data frame. Edit the data below to include information about your team members.

```{r setup-tibble}
team_data <- tibble(
  name = c("Jamie Burrell", "Charlie Franklin-White", "Dru Keiri", 
           "Sean Wang", "Annie Loi", "Duncun Hoyland"),
  github_username = c("jamie-burrell", "cfranklinwhite", "squarehedge34", 
                      "sw-005", "aaaannniie", "duncan-hoyland"), 
  colour = c("blue", "blue", "purple", 
             "green", "blue", "seagreen"),
  hobby = c("climbing", "poker", "basketball", 
            "gaming", "gaming", "rugby"),
  favourite_number = c(2, 2, 6, 8, 7, 2)
  )

team_data
```

### Exercise 18

We now work on visualising our data. 

```{r bar-plot}
p1 <- ggplot(data = team_data, 
             mapping = aes(x = github_username, 
                           y = favourite_number,
                           fill = colour), 
             ) +
   geom_col() +
   scale_fill_identity()
p1
```


bimodel

### Exercises 19

Change the text of the plot title and axis labels.

```{r labelled-bar-plot}
p1 + labs(x = "Insert text here", 
          y = "Insert text here",
          title = "Insert text here")
```

Modify axis, legend, and plot labels

### Exercise 20

```{r new-bar-plot}
p2 <- ggplot(team_data, aes(x = hobby)) +
  geom_bar()
p2
```

pie-chart? or limit the number of hobbies, lol...
